title: NextBeginning
description: Are you mushroom ?
google_analytics: 
show_downloads: false
twitter_username: jekyllrb
github_username:  jekyll
theme: jekyll-theme-architect

plugins:
  - jekyll-mentions

